<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cancel' => 'Abbrechen',
  'Create' => 'Erstellen',
  'Data' => 'Daten',
  'Delete' => 'Löschen',
  'Do you want to delete this item?' => 'Wollen Sie diesen Eintrag löschen?',
  'Fields with <span class="required">*</span> are required.' => 'Felder mit <span class="required">*</span> sind Pflichtfelder.',
  'Invalid request. Please do not repeat this request again.' => 'Ungültige Anfrage. Bitte wiederholen Sie diese Anfrage nicht.',
  'Manage' => 'Verwalten',
  'Relations' => 'Verknüpfungen',
  'Save' => 'Speichern',
  'Search' => 'Suche',
  'Switch to view mode to edit related records.' => 'Wechseln Sie in den Ansichtsmodus, um verknüpfte Datensätze zu bearbeiten.',
  'The requested page does not exist.' => 'Die angeforderte Seite existiert nicht.',
  'Update' => 'Aktualisieren',
  'View' => 'Ansicht',
);
