<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'tooltip.created_at' => '',
  'tooltip.default_title' => '',
  'tooltip.description' => '',
  'tooltip.hash' => '',
  'tooltip.id' => '',
  'tooltip.info_image_magick_json' => '',
  'tooltip.language' => '',
  'tooltip.mime_type' => '',
  'tooltip.p3_media_id' => '',
  'tooltip.status' => '',
  'tooltip.title' => '',
  'tooltip.type' => '',
  'tooltip.updated_at' => '',
  'P3MediaTranslations' => '@@Media-Übersetzungen@@',
  'P3Medias' => '@@Medien@@',
  'Access Append' => 'Anfügen',
  'Access Delete' => 'Löschen',
  'Access Domain' => 'Domain',
  'Access Owner' => 'Eigentümer',
  'Access Read' => 'Lesen',
  'Access Update' => 'Aktualisieren',
  'Copied From' => 'Kopiert von',
  'Created At' => 'Erstellt am',
  'Custom Data Json' => 'Daten',
  'Default Description' => 'Beschreibung',
  'Default Title' => 'Titel',
  'Description' => 'Beschreibung',
  'Hash' => 'Prüfsumme',
  'ID' => 'ID',
  'Info Image Magick Json' => 'ImageMagick Data',
  'Info Php Json' => 'PHP Data',
  'Language' => 'Sprache',
  'Mime Type' => 'MIME-Typ',
  'Name' => 'Name (Identifier)',
  'Original Name' => 'Originaler Dateiname',
  'P3 Media' => 'Media',
  'P3 Media Translation' => 'Media-Übersetzung',
  'P3 Media Translations' => 'Media-Übersetzungen',
  'P3 Medias' => 'Medien',
  'Path' => 'Pfad',
  'Size' => 'Größe',
  'Status' => 'Status',
  'Title' => 'Title',
  'Tree Parent' => 'Ordner',
  'Tree Position' => 'OrdnerPosition',
  'Type' => 'Typ',
  'Updated At' => 'Aktualisiert am',
  'relation.P3Media' => 'Basis-Datensatz',
  'relation.P3MediaTranslations' => 'Übersetzungen',
  'relation.P3Medias' => 'Mediendateien',
  'relation.TreeParent' => 'Ordner',
  'tooltip.access_append' => 'Rolle, welche das Recht besitzt Unterseiten unter dieser Seite anzulegen.',
  'tooltip.access_delete' => 'Rolle, welche das Recht besitzt diese Seite zu löschen.',
  'tooltip.access_domain' => 'Zugriffseinschränkung über die Anwendungssprache.',
  'tooltip.access_owner' => 'Besitzer dieses Datensatzes.',
  'tooltip.access_read' => 'Rolle, welche das Recht besitzt diese Seite zu lesen/aufzurufen.',
  'tooltip.access_update' => 'Rolle, welche das Recht besitzt diese Seite zu aktualisieren.',
  'tooltip.copied_from_id' => 'Datensatz-ID von welcher dieser Datensatz kopiert wurde.',
  'tooltip.custom_data_json' => 'Datenbereich für zusätzliche Informationen.',
  'tooltip.default_description' => 'Beschreibungstext dieser Datei.',
  'tooltip.info_php_json' => 'Daten von getimagesize()',
  'tooltip.name_id' => 'Name-ID, z.B. zur Verwendung in der Navigationsauswahl "Navbar".',
  'tooltip.original_name' => 'Name unter welchem die Datei hochgeladen wurde.',
  'tooltip.path' => 'Lokaler Dateipfad',
  'tooltip.size' => 'Dateigröße in Bytes',
  'tooltip.tree_parent_id' => 'Übergeordneter Ordner.',
  'tooltip.tree_position' => 'Position dieser Seite innnerhalb der Seiten der übergeordneten Seite',
);
