<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'CRUD' => '',
  'Folders' => 'Ordner',
  'ID' => '',
  'Import' => 'Import',
  'Select Folder' => 'Ordner auswählen',
  'Uploaded Files' => 'Hochgeladende Dateien',
  'Add files by drag & drop or by clicking the select button below' => 'Fügen Sie Dateien per Drag&Drop oder mit einem Klick auf "Dateien auswählen" hinzu',
  'Advanced Search' => '@@Erweiterte Suche@@',
  'Browse' => 'Übersicht',
  'Browser' => 'Übersicht',
  'CKEditor Browser' => '',
  'Click Start upload' => 'Klicken Sie Start upload',
  'Create File' => 'Datei erstellen',
  'Create Folder' => 'Ordner erstellen',
  'Do you want to delete this item?' => 'Wollen Sie dieses Element wirklich löschen?',
  'Download' => 'Herunterladen',
  'File Browser' => 'Dateibrowser',
  'Manage' => 'Verwalten',
  'Media' => 'Medien',
  'Media Browser' => 'Medienübersicht',
  'Overview' => 'Übersicht',
  'Please choose an image preset.' => 'Bitte wählen Sie eine Bild-Voreinstellung.',
  'Reload' => 'Aktualisieren',
  'Scan' => 'Scannen',
  'Scan import directory' => 'Importverzeichnis scannen',
  'Search' => 'Suchen',
  'Title' => 'Titel',
  'Upload' => 'Hochladen',
  'Upload Session' => 'Hochladen',
  'Upload from browser' => 'Vom Browser hochladen',
  'When upload has been completed, manage your files with' => 'Wenn das Hochladen beendet ist, verwalten Sie Ihre Dateien mit dem',
);
