<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Access Append' => '',
  'Access Delete' => '',
  'Access Domain' => '',
  'Access Owner' => '',
  'Access Read' => '',
  'Access Update' => '',
  'Copied From' => '',
  'Created At' => '',
  'Custom Data Json' => '',
  'Default Description' => '',
  'Default Title' => '',
  'Description' => '',
  'Hash' => '',
  'ID' => '',
  'Info Image Magick Json' => '',
  'Info Php Json' => '',
  'Language' => '',
  'Mime Type' => '',
  'Name' => '',
  'Original Name' => '',
  'P3 Media' => '',
  'P3 Media Translation' => '',
  'P3 Media Translations' => '',
  'P3 Medias' => '',
  'Path' => '',
  'Size' => '',
  'Status' => '',
  'Title' => '',
  'Tree Parent' => '',
  'Tree Position' => '',
  'Type' => '',
  'Updated At' => '',
  'relation.P3Media' => '',
  'relation.P3MediaTranslations' => '',
  'relation.P3Medias' => '',
  'tooltip.access_append' => '',
  'tooltip.access_delete' => '',
  'tooltip.access_domain' => '',
  'tooltip.access_owner' => '',
  'tooltip.access_read' => '',
  'tooltip.access_update' => '',
  'tooltip.copied_from_id' => '',
  'tooltip.created_at' => '',
  'tooltip.custom_data_json' => '',
  'tooltip.default_description' => '',
  'tooltip.default_title' => '',
  'tooltip.description' => '',
  'tooltip.hash' => '',
  'tooltip.id' => '',
  'tooltip.info_image_magick_json' => '',
  'tooltip.info_php_json' => '',
  'tooltip.language' => '',
  'tooltip.mime_type' => '',
  'tooltip.name_id' => '',
  'tooltip.original_name' => '',
  'tooltip.p3_media_id' => '',
  'tooltip.path' => '',
  'tooltip.size' => '',
  'tooltip.status' => '',
  'tooltip.title' => '',
  'tooltip.tree_parent_id' => '',
  'tooltip.tree_position' => '',
  'tooltip.type' => '',
  'tooltip.updated_at' => '',
);
