<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '1. Choose Format' => '',
  '2. Choose File' => '',
  'Add files by drag & drop or by clicking the select button below' => '',
  'Advanced Search' => '',
  'Browse' => '',
  'Browser' => '',
  'CKEditor Browser' => '',
  'CRUD' => '',
  'Click Start upload' => '',
  'Create File' => '',
  'Create Folder' => '',
  'Do you want to delete this item?' => '',
  'Download' => '',
  'File Browser' => '',
  'Folders' => '',
  'ID' => '',
  'Import' => '',
  'Manage' => '',
  'Media' => '',
  'Media Browser' => '',
  'Overview' => '',
  'Please choose an image preset.' => '',
  'Reload' => '',
  'Scan' => '',
  'Scan import directory' => '',
  'Search' => '',
  'Select Folder' => '',
  'Title' => '',
  'Upload' => '',
  'Upload Session' => '',
  'Upload from browser' => '',
  'Uploaded Files' => '',
  'When upload has been completed, manage your files with' => '',
);
